### ISSUE TITLE
Add Invert setting for RFLinkContactSensor

### ISSUE THREAD

**Issue by Redferne** [sirchia/pimatic-rflink#8]
I have a bunch of ContactSensors that report a inverted value. So the door is always open in the Pimatic GUI however it's very closed. The same function is available in the RFLinkPir type.

**Comment by sirchia** [comment]
Thanks for reporting this issue.
I pushed some changes that should fix it, but I don't have the necessary devices to test it out.
Can you try out the current master branch to see if the issue is fixed and post your results here.
I will make a new release if the tests are successful.

**Comment by Redferne** [comment]
Latest @master works perfectly. Thank you!

**Comment by sirchia** [comment]
Issue closed. 
Bugfix in release 0.6.0
